require 'user/options'
require 'user/keybinds'
require 'user/plugins'
require 'user/colorscheme'
require 'user/cmp'
require 'user/telescope'
require 'user/treesitter'
require 'user/lsp'
require 'user/gitsigns'
require 'user/autopairs'
require 'user/nvimtree'
-- require 'user/bufferline' Now using harpoon
require 'user/harpoon'
require 'user/lualine'
require 'user/which-key'
-- require 'ufo'
-- require ''
